services:
  tsdmd:
    build: .
    restart: unless-stopped
    user: "1000:1000"  # use command id to get these values
    env_file: .env
    volumes:
      - ./sessions:/app/sessions
      - ./Media:/app/Media
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL